lib-suffix := if os() == "windows" { ".dll" } else { "" }
bin-suffix := if os() == "windows" { ".exe" } else { ".out" }
# TODO: use UMDH here for windows?
# https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/umdh
valgrind-command := if os() == "windows" { "echo 'valgrind not supported on windows'" } else { "./scripts/valgrind-command.sh" }
test-command := if os() == "windows" { "./scripts/test-command.bat" } else { "./scripts/test-command.sh" }
clang-checks := if os() == "windows" { "-Werror -Wunused-variable -Werror=sign-compare -Wincompatible-pointer-types" } else { "-Wall -Werror -Wunused-variable -Werror=sign-compare -Wincompatible-pointer-types" }
default-target:= "debug"

build target=default-target:
    cargo build --verbose --profile={{ if target == "debug" {"dev"} else { target } }}

build-test-rust target=default-target:  (build target)
    cargo test --verbose --profile={{ if target == "debug" {"dev"} else { target } }} -- --test-threads 1

build-tests-capi target=default-target: (build target)
    clang \
    {{ clang-checks }} \
    {{ if target == "debug" { "-D DEBUG" } else { "-O3" } }} \
    tests_capi/*.c \
    tests_capi/munit/munit.c \
    -Iinclude \
    -o bin/test_c{{bin-suffix}} \
    -l hyperlight_host{{lib-suffix}} \
    -L../../target/{{target}}

run-tests-capi target=default-target: (build-tests-capi target)
    {{test-command}} {{target}}
valgrind-tests-capi target=default-target: (build-tests-capi target)
    GEN_SUPPRESSIONS_ON=1 LOG_FILE_ON=0 {{valgrind-command}} {{target}}
valgrind-tests-capi-gen-suppressions target=default-target: (build-tests-capi target)
    GEN_SUPPRESSIONS_ON=1 LOG_FILE_ON=1 {{valgrind-command}} {{target}} 1
