// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod hyperlight {
  use super::*;
  pub mod generated {
    use super::*;
    mod parameter_value_generated;
    pub use self::parameter_value_generated::*;
    mod parameter_type_generated;
    pub use self::parameter_type_generated::*;
    mod return_type_generated;
    pub use self::return_type_generated::*;
    mod return_value_generated;
    pub use self::return_value_generated::*;
    mod hlint_generated;
    pub use self::hlint_generated::*;
    mod hllong_generated;
    pub use self::hllong_generated::*;
    mod hlstring_generated;
    pub use self::hlstring_generated::*;
    mod hlbool_generated;
    pub use self::hlbool_generated::*;
    mod hlvecbytes_generated;
    pub use self::hlvecbytes_generated::*;
    mod hlsizeprefixedbuffer_generated;
    pub use self::hlsizeprefixedbuffer_generated::*;
    mod hlvoid_generated;
    pub use self::hlvoid_generated::*;
    mod host_function_definition_generated;
    pub use self::host_function_definition_generated::*;
    mod host_function_details_generated;
    pub use self::host_function_details_generated::*;
  } // generated
} // hyperlight
